### ISSUE TITLE
f4 closes micro

### ISSUE THREAD

**Issue by benzmuircroft** [terokarvinen/micro-jump#3]
ctrl+e
plugin install jump
close micro
open a file with micro
press f4

**result:** f4 closes micro

shouldn't it "Jump"?

**Comment by benjamin-thomas** [comment]
For me, `F4` did close the editor prior to plugin installation.

`F4` was then rebound to function search so it's all good.

I suppose this could be closed and you may have to update your binary?

```
$ micro --version
Version: 2.0.11
Commit hash: 225927b9
Compiled on August 01, 2022
```

**Comment by Heart1010** [comment]
I'm using putty terminal and when I press `F4` in micro the only thing happens is it add `14~`f as text 🤔 

```bash
$ micro --version
Version: 2.0.12
Commit hash: c2cebaa3
Compiled on September 06, 2023

t$ cat ~/.config/micro/bindings.json
{
    "Alt-/": "lua:comment.comment",
    "Alt-j": "lua:joinLines.joinLines",
    "CtrlUnderscore": "lua:comment.comment",
    "F4": "command:jumptag"
}
```

**Comment by terokarvinen** [comment]
Have you tried mapping "command:jumptag" to another key? 

Depending on your environment, not all keys are available for binding. I use micro-jump on Linux, and have not tested it on Windows.

**Comment by Heart1010** [comment]
> Have you tried mapping "command:jumptag" to another key?
> 
> Depending on your environment, not all keys are available for binding. I use micro-jump on Linux, and have not tested it on Windows.

Found the solution - see updated post above. Thanks!

**Comment by terokarvinen** [comment]
Happy to hear that, Heart1010. 

Are you using Windows?

Which key did you successfully map?
